<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <BoostRegexIncludeDir>$(SolutionDir)external\regex-boost-1.92.0\include\</BoostRegexIncludeDir>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(BoostRegexIncludeDir.TrimEnd('\\'));%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
	  <PreprocessorDefinitions>BOOST_REGEX_STANDALONE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="BoostRegexIncludeDir">
      <Value>$(BoostRegexIncludeDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>